from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class SharedGate(str, Enum):
    STABLE_SHARED = "stable_shared"
    AGGREGATE_ONLY = "aggregate_only"
    EXPERIMENTAL = "experimental"
    BLOCKED = "blocked"


@dataclass(frozen=True)
class SharedTagEntry:
    dim: str
    scope: str
    gate: SharedGate
    script_verdict: str
    video_verdict: str
    reason: str
    tag_set_ver: str


# AUTOGENERATED BELOW. Regenerated by `python -m cli.run_cross_modal_alignment`.
# Placeholder only: wait for real script/video stability experiment results.
SHARED_TAG_GATES: tuple[SharedTagEntry, ...] = ()


def list_entries() -> tuple[SharedTagEntry, ...]:
    return SHARED_TAG_GATES


def list_dims_by_gate(gate: SharedGate | str) -> tuple[str, ...]:
    gate_value = SharedGate(gate)
    return tuple(entry.dim for entry in SHARED_TAG_GATES if entry.gate == gate_value)


def get_entry(dim: str) -> SharedTagEntry | None:
    for entry in SHARED_TAG_GATES:
        if entry.dim == dim:
            return entry
    return None
