from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class SharedGate(str, Enum):
    STABLE_SHARED = "stable_shared"
    AGGREGATE_ONLY = "aggregate_only"
    EXPERIMENTAL = "experimental"
    BLOCKED = "blocked"


@dataclass(frozen=True)
class SharedTagEntry:
    dim: str
    scope: str
    gate: SharedGate
    script_verdict: str
    video_verdict: str
    reason: str
    tag_set_ver: str


# AUTOGENERATED BELOW. Regenerated by `python -m cli.run_cross_modal_alignment`.
SHARED_TAG_GATES: tuple[SharedTagEntry, ...] = (
    SharedTagEntry(
        dim="world_setting",
        scope="script",
        gate=SharedGate.STABLE_SHARED,
        script_verdict="online",
        video_verdict="video_stable",
        reason="both sides are stable",
        tag_set_ver="v1.0.0",
    ),
    SharedTagEntry(
        dim="scene_emotion_keynote",
        scope="plot_unit",
        gate=SharedGate.STABLE_SHARED,
        script_verdict="online",
        video_verdict="video_stable",
        reason="both sides are stable",
        tag_set_ver="v2.0.0",
    ),
    SharedTagEntry(
        dim="relationship_polarity",
        scope="relationship",
        gate=SharedGate.EXPERIMENTAL,
        script_verdict="online",
        video_verdict="video_experimental",
        reason="at least one side is experimental/fix",
        tag_set_ver="v1.0.0",
    ),
    SharedTagEntry(
        dim="gender_axis",
        scope="script",
        gate=SharedGate.AGGREGATE_ONLY,
        script_verdict="online",
        video_verdict="video_aggregate",
        reason="video side requires aggregation",
        tag_set_ver="v1.0.0",
    ),
    SharedTagEntry(
        dim="scene_locale_type",
        scope="plot_unit",
        gate=SharedGate.AGGREGATE_ONLY,
        script_verdict="online",
        video_verdict="video_aggregate",
        reason="video side requires aggregation",
        tag_set_ver="v2.0.0",
    ),
)


def list_entries() -> tuple[SharedTagEntry, ...]:
    return SHARED_TAG_GATES


def list_dims_by_gate(gate: SharedGate | str) -> tuple[str, ...]:
    gate_value = SharedGate(gate)
    return tuple(entry.dim for entry in SHARED_TAG_GATES if entry.gate == gate_value)


def get_entry(dim: str) -> SharedTagEntry | None:
    for entry in SHARED_TAG_GATES:
        if entry.dim == dim:
            return entry
    return None
